### ISSUE TITLE
Question about the Application layer

### ISSUE THREAD

**Issue by cant0r** [gorogdemi/Wallet#9]
Hi Team,

I'm trying to understand the Clean Architecture based on your `dq-wallet` project.

I've noticed that you use `DbSet<T>` in your Application layer inside [IWalletContext](https://github.com/devquarter/dq-wallet/blob/main/Application/Common/Interfaces/IWalletContext.cs). 
Shouldn't this live inside the Infrastructure layer as this type belongs to Entity Framework? I thought the Application layer should not know about external services and should only communicate with them through high-level interfaces.

**Comment by gorogdemi** [comment]
Clean Architecture defines some "standards" which are used solution-wide (like MediatR or AutoMapper). EF falls to this category as well. Note that the IWalletContext is just an interface which contains only abstractions from EF (DbSet). The actual implementation (WalletContext) is in the Infrastructure project.

**Comment by cant0r** [comment]
That makes sense, thank you!
